site:
  name: "Metaphor"
related_parties:
  singular: "Artist"
  plural: "Artists"
articles:
  singular: "Article"
  plural: "Articles"
categories:
  singular: "Category"
  plural: "Categories"
series:
  singular: "Series"
  plural: "Series"
collections:
  singular: "Collection"
  plural: "Collections"
pages:
  singular: "Static Page"
  plural: "Static Pages"
users:
  singular: "User"
  plural: "Users"
  
query:
  types:
    all: All
    video: Video
    sound: Sound
    gallery: Gallery
    event: Event
  order:
    newest: Newest
    oldest: Oldest
    hottest: Hottest
    
templates:
  video:
    name: Video
    image: http://nicenicejpg.com/72/128
    widgets:
      topvideo: topvideo
      meta: meta
      body: body
  sound:
    name: Sound
    image: http://nicenicejpg.com/72/128
    widgets:
      topimage: topimage
      meta: meta
      sound: sound
      body: body
  gallery:
    name: Gallery
    image: http://nicenicejpg.com/72/128
    widgets:
      topgallery: topgallery
      meta: meta
      body: body
  text:
    name: Text
    image: http://nicenicejpg.com/72/128
    widgets:
      topimage: topimage
      meta: meta
      body: body